Repository kids-first/kf-germline-workflow, pull requests merged in 2022-09, with the labels that each got.

#22 📚 germline sv release prep
  docs/GERMLINE_SV_README.md
  tools/svaba.cwl
  workflows/kfdrc-germline-sv-wf.cwl
Labels: documentation, feature, bix-dev

#23 🚀 Add germline SNV Workflow
  docs/GERMLINE_SNV_ANNOT_README.md
  tools/bcftools_annotate.cwl
  tools/bcftools_filter_vcf.cwl
  tools/bcftools_strip_ann.cwl
  tools/generic_rename_outputs.cwl
  tools/normalize_vcf.cwl
  tools/variant_effect_predictor_105.cwl
  workflows/kfdrc-germline-snv-annot-workflow.cwl
Labels: documentation, feature, bix-dev

#24 💪 Add annotation workflow and upgrade
  docs/GATK_GERMLINE_README.md
  docs/GERMLINE_SNV_ANNOT_README.md
  tools/bcftools_annotate.cwl
  tools/variant_effect_predictor.cwl
  workflows/kfdrc-germline-snv-annot-workflow.cwl
  workflows/kfdrc-single-sample-genotyping-wf.cwl
Labels: documentation, feature, bix-dev

#25 🔧 Bug/fix secondary file ref
  workflows/kfdrc-germline-snv-annot-workflow.cwl
  workflows/kfdrc-single-sample-genotyping-wf.cwl
Labels: bug, bix-dev

#26 ✏️ allow `tool_name` to do the heavy lifting
  workflows/kfdrc-germline-snv-annot-workflow.cwl
  workflows/kfdrc-single-sample-genotyping-wf.cwl
Labels: bug, documentation, bix-dev
